# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_Rort_wrappers", use_symbols = TRUE, package_name = "Rort")

#' @usage NULL
#' @useDynLib Rort, .registration = TRUE
NULL

#' @export
hello_world <- function() .Call(wrap__hello_world)


# nolint end
